# Site settings
title: Adriano Latorre
description: "Portfolio"
baseurl: ""
url: "http://adriano.latorre.info"
twitter_username: adrianolatorre
github_username:  adrianolatorre

# Collections
collections:
  books:
    output: false
    permalink: /books/:path/
  links:
    output: false
    permalink: /links/:path/
  people:
    output: false
    permalink: /people/:path/
  projects:
    output: false
    permalink: /projects/:path/
  the_wick:
    output: false
    permalink: /w/:path/
  work:
    output: false
    permalink: /work/:path/

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - node_modules
