# Site settings
title: Adriano Latorre
description: "Portfolio"
baseurl: ""
url: "http://adriano.latorre.info"
twitter_username: adrianolatorre
github_username:  adrianolatorre

# Collections
collections:
  the_wick:
    output: false
    permalink: /w/:path/

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - node_modules
