
- title: "Adactio"
  www: "https://adactio.com/"
  tags:
    - blog
    - collection
    - css
    - link
    - web

- title: "A List Apart"
  www: "http://alistapart.com/"
  tags:
    - css
    - design
    - magazine
    - tutorial

- title: "A Working Library"
  www: "http://aworkinglibrary.com/"
  tags:
    - blog
    - book
    - essay
    - collection

- title: "Aeon"
  www: "https://aeon.co/"
  tags:
    - magazine
    - science
    - technology

- title: "An Event Apart"
  www: "https://aneventapart.com/"
  tags:
    - css
    - design
    - tutorial
    - video

- title: "Arts & Letters Daily"
  www: "http://www.aldaily.com/"
  tags:
    - collection
    - link

- title: "Belong"
  www: "http://belong.io/"
  tags:
    - collection
    - link

- title: "Book Marks"
  www: "http://lithub.com/bookmarks/"
  tags:
    - book
    - collection

- title: "Brutalist Websites"
  www: "http://brutalistwebsites.com/"
  tags:
    - collection
    - design
    - inspiration
    - link
    - web

- title: "Clive Thompson"
  www: "http://clivethompson.net/"
  tags:
    - blog
    - collection
    - future
    - link
    - technology

- title: "Coudal Fresh Signals"
  www: "http://www.coudal.com/"
  tags:
    - collection
    - link

- title: "Daring Fireball"
  www: "http://daringfireball.net/"
  tags:
    - apple
    - blog
    - technology

- title: "Ethan Marcotte"
  www: "https://ethanmarcotte.com/wrote/"
  tags:
    - blog
    - design
    - web

- title: "Every Frame a Painting"
  www: "https://www.youtube.com/user/everyframeapainting"
  tags:
    - analysis
    - film
    - video

- title: "FormFiftyFive"
  www: "https://formfiftyfive.com/"
  tags:
    - collection
    - design
    - inspiration
    - link

- title: "httpster"
  www: "https://httpster.net/"
  tags:
    - collection
    - design
    - inspiration
    - link
    - web

- title: "Kottke"
  www: "http://kottke.org/"
  tags:
    - blog
    - collection
    - link

- title: "Longform"
  www: "https://longform.org/"
  tags:
    - article
    - collection
    - link

- title: "Longreads"
  www: "https://longreads.com/"
  tags:
    - article
    - collection
    - link

- title: "Nautilus"
  www: "http://nautil.us/"
  tags:
    - magazine
    - science
    - technology

- title: "Pinboard popular bookmarks"
  www: "http://pinboard.in/popular/"
  tags:
    - collection
    - link

- title: "Quanta Magazine"
  www: "https://www.quantamagazine.org/"
  tags:
    - magazine
    - science
    - technology

- title: "Refind"
  www: "https://refind.com/"
  tags:
    - collection
    - link

- title: "siteinspire"
  www: "https://www.siteinspire.com/websites"
  tags:
    - collection
    - design
    - inspiration
    - link
    - web

- title: "The Electric Typewriter"
  www: "http://tetw.org/"
  tags:
    - article
    - essay
    - collection

- title: "The Exponential View"
  www: "https://www.getrevue.co/profile/azeem"
  tags:
    - ai
    - future
    - newsletter

- title: "The Latest"
  www: "http://latest.is/"
  tags:
    - bot
    - collection
    - link

- title: "The Nerdwriter"
  www: "https://www.youtube.com/user/Nerdwriter1/"
  tags:
    - video

- title: "Things magazine"
  www: "http://www.thingsmagazine.net/"
  tags:
    - collection
    - link

- title: "Typewolf"
  www: "https://www.typewolf.com/"
  tags:
    - collection
    - design
    - inspiration
    - link
    - typography
    - web

- title: "Wait but why"
  www: "http://waitbutwhy.com/"
  tags:
    - ai
    - blog
    - future
    - technology

- title: "Zeldman"
  www: "http://zeldman.com/"
  tags:
    - blog
    - design
    - web
